# -*- coding: utf-8 -*-
"""🚫 .gitignore 템플릿"""
import os
from ... import ui
from ..ui import C, GoBack


TEMPLATES = {
    "Python": """__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
.env
.venv
*.egg-info/
dist/
build/
.pytest_cache/
.mypy_cache/
""",
    "Node.js": """node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.env
.env.local
dist/
build/
.next/
.nuxt/
""",
    "Java": """*.class
*.jar
*.war
target/
.gradle/
build/
.idea/
*.iml
""",
    "macOS": """.DS_Store
.AppleDouble
.LSOverride
Icon
._*
.Spotlight-V100
.Trashes
""",
    "VS Code": """.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
""",
    "JetBrains": """.idea/
*.iml
*.iws
*.ipr
out/
""",
    "Xcode": """build/
*.xcodeproj/xcuserdata/
*.xcworkspace/xcuserdata/
DerivedData/
*.xcuserstate
""",
}


def run(repo):
    path = os.path.join(repo, ".gitignore")
    exists = os.path.exists(path)

    items = [{"label": k, "value": k} for k in TEMPLATES.keys()]
    selected = ui.checklist(
        "Gitignore",
        items,
        prompt="사용할 템플릿을 선택하세요 (복수 선택)"
    )

    if not selected:
        ui.warn("선택된 템플릿 없음")
        ui.pause()
        return

    content = "# Generated by Easy Git\n\n"
    for k in selected:
        content += f"# ─── {k} ───\n{TEMPLATES[k]}\n"

    if exists:
        if ui.confirm("기존 파일에 추가? (No=덮어쓰기)", True):
            mode = "a"
        else:
            mode = "w"
    else:
        mode = "w"

    with open(path, mode, encoding="utf-8") as fp:
        fp.write(content)
    ui.success(f".gitignore {'추가됨' if mode == 'a' else '생성됨'}")
    ui.pause()
